import type { DashboardData } from "./api";

export const mockDashboardData: DashboardData = {
    total_optimizations: 47,
    total_kwh_saved: 12.83,
    total_co2_saved: 5.41,
    total_eur_saved: 3.21,
    sustainability_score: 78,
    history: [
        {
            id: 1,
            timestamp: "2026-02-22T10:30:00Z",
            filename: "matrix_multiply.cpp",
            patterns_found: 3,
            energy_before: 82.5,
            energy_after: 34.2,
            savings_kwh: 0.0048,
            savings_co2_kg: 0.0020,
            savings_eur: 0.0012,
            original_code: `void multiply(int** A, int** B, int** C, int n) {\n  for (int i = 0; i < n; i++)\n    for (int j = 0; j < n; j++)\n      for (int k = 0; k < n; k++)\n        C[i][j] += A[i][k] * B[k][j];\n}`,
            optimized_code: `void multiply(int** A, int** B, int** C, int n) {\n  for (int i = 0; i < n; i++)\n    for (int k = 0; k < n; k++)\n      for (int j = 0; j < n; j++)\n        C[i][j] += A[i][k] * B[k][j];\n}`,
            chain_of_thought: "Reordered loop indices to improve cache locality. The k-j swap ensures sequential memory access for matrix B, reducing cache misses by ~60%.",
        },
        {
            id: 2,
            timestamp: "2026-02-21T15:45:00Z",
            filename: "data_pipeline.py",
            patterns_found: 2,
            energy_before: 65.0,
            energy_after: 28.0,
            savings_kwh: 0.0037,
            savings_co2_kg: 0.0016,
            savings_eur: 0.0009,
        },
        {
            id: 3,
            timestamp: "2026-02-20T09:15:00Z",
            filename: "sort_utils.cpp",
            patterns_found: 1,
            energy_before: 90.0,
            energy_after: 42.0,
            savings_kwh: 0.0052,
            savings_co2_kg: 0.0022,
            savings_eur: 0.0013,
        },
        {
            id: 4,
            timestamp: "2026-02-19T14:00:00Z",
            filename: "image_proc.py",
            patterns_found: 4,
            energy_before: 75.0,
            energy_after: 30.0,
            savings_kwh: 0.0045,
            savings_co2_kg: 0.0019,
            savings_eur: 0.0011,
        },
        {
            id: 5,
            timestamp: "2026-02-18T11:20:00Z",
            filename: "api_handler.cpp",
            patterns_found: 2,
            energy_before: 55.0,
            energy_after: 25.0,
            savings_kwh: 0.0030,
            savings_co2_kg: 0.0013,
            savings_eur: 0.0008,
        },
        {
            id: 6,
            timestamp: "2026-02-17T16:30:00Z",
            filename: "db_queries.py",
            patterns_found: 3,
            energy_before: 70.0,
            energy_after: 32.0,
            savings_kwh: 0.0038,
            savings_co2_kg: 0.0016,
            savings_eur: 0.0010,
        },
    ],
};
